import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '@/styles/Home.module.css'
import NavBar from '@/components/navbar'
import { Col, Row, } from 'reactstrap'
import Banner from '@/components/banner'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/imgs/J_W dark noB - fav.svg" />
      </Head>
      <div id="content">
        <NavBar />
        <Banner height='70vh' imgPaths={['/imgs/forest-lg.jpg', '/imgs/forest-sm.jpg']}>
        <img className="me-3" style={{height: '2em'}} src="/imgs/J_W white noB.svg"/>
        <div style={{fontFamily: "'Montserrat', serif", lineHeight: 1}}>
          Jackson <span className='display_mobile'></span>Wilding
        </div>
        </Banner>
        <Row > 
          <Col >
          <h3 className="mb-0">Bio</h3>
          </Col>
        </Row>
      </div>      
    </>
  )
}
